### ISSUE TITLE
Compilation fails under openSUSE Leap 15.2

### ISSUE THREAD

**Issue by kentaurest** [open-eid/libdigidocpp#399]
[   45s] [ 30%] Building CXX object src/CMakeFiles/digidocpp_priv.dir/crypto/TSL.cpp.o
[   45s] cd /home/abuild/rpmbuild/BUILD/libdigidocpp/src && /usr/bin/g++-9  -DBUILD_DATE=\"13.08.2010\" -DBUILD_VER=0 -DMAJOR_VER=3 -DMINOR_VER=14 -DRELEASE_VER=5 -DVER_SUFFIX=\"\" -Ddigidocpp_EXPORTS -I/home/abuild/rpmbuild/BUILD/libdigidocpp/src  -std=gnu++11 -O2 -g -DNDEBUG -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -std=gnu++11 -o CMakeFiles/digidocpp_priv.dir/crypto/TSL.cpp.o -c /home/abuild/rpmbuild/BUILD/libdigidocpp/src/crypto/TSL.cpp
[   46s] /home/abuild/rpmbuild/BUILD/libdigidocpp/src/crypto/TSL.cpp: In member function 'void digidoc::TSL::validate(const std::vector<digidoc::X509Cert>&)':
[   46s] /home/abuild/rpmbuild/BUILD/libdigidocpp/src/crypto/TSL.cpp:521:38: error: invalid conversion from 'const char16_t*' to 'const XMLCh*' {aka 'const short unsigned int*'} [-fpermissive]
[   46s]   521 |         sig->registerIdAttributeName(u"ID");
[   46s]       |                                      ^~~~~
[   46s]       |                                      |
[   46s]       |                                      const char16_t*
[   46s] In file included from /usr/include/xsec/framework/XSECProvider.hpp:33,
[   46s]                  from /home/abuild/rpmbuild/BUILD/libdigidocpp/src/crypto/TSL.cpp:37:
[   46s] /usr/include/xsec/dsig/DSIGSignature.hpp:933:45: note: initializing argument 1 of 'void DSIGSignature::registerIdAttributeName(const XMLCh*)'
[   46s]   933 |  void registerIdAttributeName(const XMLCh * name);
[   46s]       |                               ~~~~~~~~~~~~~~^~~~
[   46s] make[2]: *** [src/CMakeFiles/digidocpp_priv.dir/build.make:353: src/CMakeFiles/digidocpp_priv.dir/crypto/TSL.cpp.o] Error 1
[   46s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/libdigidocpp'
[   46s] make[1]: *** [CMakeFiles/Makefile2:162: src/CMakeFiles/digidocpp_priv.dir/all] Error 2
[   46s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/libdigidocpp'
[   46s] make: *** [Makefile:161: all] Error 2
[   46s] error: Bad exit status from /var/tmp/rpm-tmp.tdjZMl (%build

**Comment by metsma** [comment]
Fixed in PR #391

**Comment by akbgf** [comment]
Hi!
The same compilation error is still there under openSUSE Leap 15.1 on 22 February 2021.
And similar error I got compiling DigiDoc4-Client cloned from Git on 22.02.2021:
[ 30%] Building CXX object client/CMakeFiles/qdigidoc4.dir/Application.cpp.o
/home/andres/sw/linux/id_kaart/DigiDoc4-Client/client/Application.cpp: In constructor ‘Application::Application(int&, char**)’:
/home/andres/sw/linux/id_kaart/DigiDoc4-Client/client/Application.cpp:393:3: error: cannot convert ‘const char*’ to ‘digidoc::initCallBack {aka void (*)(const digidoc::Exception*)}’ for argument ‘2’ to ‘void digidoc::initialize(const string&, digidoc::initCallBack)’
   );
   ^

**Comment by kristelmerilain** [comment]
> Hi!
> The same compilation error is still there under openSUSE Leap 15.1 on 22 February 2021.
> And similar error I got compiling DigiDoc4-Client cloned from Git on 22.02.2021:
> [ 30%] Building CXX object client/CMakeFiles/qdigidoc4.dir/Application.cpp.o
> /home/andres/sw/linux/id_kaart/DigiDoc4-Client/client/Application.cpp: In constructor ‘Application::Application(int&, char**)’:
> /home/andres/sw/linux/id_kaart/DigiDoc4-Client/client/Application.cpp:393:3: error: cannot convert ‘const char*’ to ‘digidoc::initCallBack {aka void (_)(const digidoc::Exception_)}’ for argument ‘2’ to ‘void digidoc::initialize(const string&, digidoc::initCallBack)’
> );
> ^

Did you used master branch when you tested on February 22nd? 
PR #391 was merged into master on March 4th. Please try again with the latest master.

**Comment by akbgf** [comment]
Hi!

Tue, 27 Apr 2021, Kristel Merilain:

>> The same compilation error is still there under openSUSE Leap 15.1 on 22 February 2021.
>> And similar error I got compiling DigiDoc4-Client cloned from Git on 22.02.2021:
> [..]
>
> Did you used master branch when you tested on February 22nd?
> PR #391 was merged into master on March 4th. Please try again with the latest master.

Last week I upgraded openSUSE-15.1 to openSUSE-15.3.
On 28 April 2021 the set of ID-software at https://github.com/open-eid/ compiles:

libdigidoc
libdigidocpp
DigiDoc4-Client

chrome-token-signing could be installed in Firefox seraching Extension 
'Token signing'.


Estonian ID-card is working on openSUSE-15.3.

Thank you!

Andres Kuusk
Tartu Observatory, Tõravere
